<!--
title:   com.sforce.soap.enterprise.SaveResultのエラーメッセージ取得
tags:    Salesforce,ja
id:      4113088aafb4d48d780b
private: false
-->
`java
SaveResult[] sr = binding.create((new SObject[] {c}));
// ログを出力
for (int j = 0; j < sr.length; j++) {
    System.out.println("\nItem: " + j);
    if (sr[j].isSuccess()) {	                            
        System.out.println("Contact with an ID of " + sr[j].getId() + " was updated.");
    } else {                        
        // There were errors during the update call,
        // go through the errors array and write
        // them to the console.
        for (int i1 = 0; i1 < sr[j].getErrors().length; i1++) {
            com.sforce.soap.enterprise.Error err = sr[j].getErrors()[i1];  
            System.out.println("Errors were found on item " + j);
            System.out.println("Error code: " + err.getStatusCode().toString());
            System.out.println("Error message: " + err.getMessage());
        }
    }      
}  